version: "3.9"
services:
  mysql-service:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql-service
    networks:
      - workflow
    environment:
      MYSQL_ROOT_PASSWORD: Negi@123
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Negi@123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongo-service:
    image: mongo:latest
    container_name: mongo-service
    networks:
      - workflow
    ports:
      - "27017:27017"

  eureka-service:
    container_name: eureka-service
    build: EurekaServer/
    ports:
      - "8761:8761"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    restart: always
    networks:
      - workflow

  api-gateway-service:
    container_name: api-gateway-service
    build: APIGateway/
    networks:
      - workflow
    ports:
      - "8085:8085"
    restart: always

  auth-service:
    build: FinalProject/
    container_name: auth-service
    networks:
      - workflow
    ports:
      - "3033:3033"
    depends_on:
      - mysql-service
      - eureka-service
    restart: always

  kanban-service:
    container_name: kanban-service
    build: kanban/
    networks:
      - workflow
    ports:
      - "8007:8007"
    links:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - mongo-service
      - rabbitmq
      - eureka-service
    restart: always

  notification-service:
    container_name: notification-service
    build: notification/
    networks:
      - workflow
    ports:
      - "8090:8090"
    links:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - mongo-service
      - rabbitmq
      - eureka-service
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - workflow

networks:
  workflow:
    driver: bridge